name: grocery-ml-xgb
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - annotated-types=0.7.0
  - anyio=4.12.0
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - asttokens=3.0.1
  - async-lru=2.0.5
  - attrs=25.4.0
  - aws-c-auth=0.9.3
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.7
  - aws-c-http=0.10.7
  - aws-c-io=0.23.3
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.11.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.4
  - aws-sdk-cpp=1.11.606
  - babel=2.17.0
  - backports.zstd=1.3.0
  - beautifulsoup4=4.14.3
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - catalogue=2.0.10
  - certifi=2026.1.4
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.3.1
  - cloudpathlib=0.23.0
  - cloudpickle=3.1.2
  - colorama=0.4.6
  - comm=0.2.3
  - confection=0.1.5
  - contourpy=1.3.2
  - cuda-cudart=12.9.79
  - cuda-cudart_win-64=12.9.79
  - cuda-version=12.9
  - cycler=0.12.1
  - cymem=2.0.13
  - cython-blis=1.3.3
  - debugpy=1.8.19
  - decorator=5.2.1
  - defusedxml=0.7.1
  - double-conversion=3.4.0
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - fqdn=1.5.1
  - freetype=2.14.1
  - graphite2=1.3.14
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=12.3.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=78.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=7.1.0
  - ipython=8.37.0
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.3
  - json5=0.13.0
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.7.0
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.5.1
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lark=1.3.1
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250512.1
  - libarrow=22.0.0
  - libarrow-acero=22.0.0
  - libarrow-compute=22.0.0
  - libarrow-dataset=22.0.0
  - libarrow-substrait=22.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang13=21.1.7
  - libcrc32c=1.1.2
  - libcurl=8.17.0
  - libdeflate=1.25
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libglib=2.86.3
  - libgomp=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libparquet=22.0.0
  - libpng=1.6.53
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - libsodium=1.0.20
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libutf8proc=2.11.2
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxgboost=3.1.2
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - llvmlite=0.46.0
  - lz4-c=1.10.0
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mdurl=0.1.2
  - mistune=3.2.0
  - mkl=2025.3.0
  - munkres=1.1.4
  - murmurhash=1.0.15
  - nbclient=0.10.4
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - notebook=7.5.1
  - notebook-shim=0.2.4
  - numba=0.63.1
  - numpy=2.2.6
  - openjpeg=2.5.4
  - openpyxl=3.1.5
  - openssl=3.6.0
  - orc=2.2.1
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandocfilters=1.5.0
  - parso=0.8.5
  - pcre2=10.47
  - pickleshare=0.7.5
  - pillow=12.1.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.1
  - preshed=3.0.12
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - psutil=7.2.1
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - py-xgboost=3.1.2
  - pyarrow=22.0.0
  - pyarrow-core=22.0.0
  - pycparser=2.22
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - pygments=2.19.2
  - pyparsing=3.3.1
  - pyside6=6.10.1
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=2.0.7
  - python-tzdata=2025.3
  - python_abi=3.10
  - pytz=2025.2
  - pywin32=311
  - pywinpty=2.0.15
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt6-main=6.10.1
  - rapidfuzz=3.14.3
  - re2=2025.11.05
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rich=14.2.0
  - rpds-py=0.30.0
  - scikit-learn=1.7.2
  - scipy=1.15.2
  - send2trash=2.0.0
  - setuptools=80.9.0
  - shap=0.48.0
  - shellingham=1.5.4
  - six=1.17.0
  - slicer=0.0.8
  - smart-open=7.5.0
  - smart_open=7.5.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - soupsieve=2.8.1
  - spacy=3.8.11
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - srsly=2.5.2
  - stack_data=0.6.3
  - tbb=2022.3.0
  - terminado=0.18.1
  - thinc=8.3.10
  - threadpoolctl=3.6.0
  - tinycss2=1.5.1
  - tk=8.6.13
  - tomli=2.3.0
  - tornado=6.5.4
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typer=0.21.0
  - typer-slim=0.21.0
  - typer-slim-standard=0.21.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025c
  - ucrt=10.0.26100.0
  - ujson=5.11.0
  - unicodedata2=17.0.0
  - uri-template=1.3.0
  - urllib3=2.6.2
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - wasabi=1.1.3
  - wcwidth=0.2.14
  - weasel=0.4.3
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - wrapt=2.0.1
  - xgboost=3.1.2
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
      - en-core-web-sm==3.8.0
prefix: C:\ProgramData\miniconda3\envs\grocery-ml-xgb
